version: '3'
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: your-mssql-container  # Replace with the desired container name
    environment:
      - SA_PASSWORD=Sirajudeen1
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express

    ports:
      - "1433:1433"  # Map host port 1433 to container port 1433
    restart: always  # Restart the container always (optional)

  node-app:
    image: your-node-image  # Replace with the name you gave to your Node.js Docker image
    container_name: your-node-container  # Replace with the desired container name
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000
    build:
      context: .
    # depends_on:
    #   mssql-server:
    #     condition: service_started
    command: sh -c "npx prisma db push && node index.js"
    environment:
      - DB_HOST=mssql-server
      - DATABASE_URL=sqlserver://mssql-server:1433;database=test;user=sa;password=Sirajudeen1;encrypt=false;trustServerCertificate=true
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=Sirajudeen1
      - DB_DATABASE=test


    restart: always  # Restart the container always (optional)
